#### Problem 1: Array Creation
Complete the following tasks:

In [1]:
import numpy as np

# 1. Initialize an empty array with size 2X2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:")
print(empty_array)
print()

# 2. Initialize an all one array with size 4X2
ones_array = np.ones((4, 2))
print("2. All ones 4x2 array:")
print(ones_array)
print()

# 3. Return a new array of given shape and type, filled with fill value
fill_array = np.full((3, 3), 7)  # Fill with value 7
print("3. 3x3 array filled with 7:")
print(fill_array)
print()

# 4. Return a new array of zeros with same shape and type as a given array
given_array = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_array = np.zeros_like(given_array)
print("4. Zeros array with same shape as given array:")
print("Given array shape:", given_array.shape)
print(zeros_like_array)
print()

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(given_array)
print("5. Ones array with same shape as given array:")
print(ones_like_array)
print()

# 6. For an existing list new_list = [1,2,3,4] convert to a numpy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("6. Converted list to numpy array:")
print("Original list:", new_list)
print("Numpy array:", numpy_array)
print("Type:", type(numpy_array))

1. Empty 2x2 array:
[[2.69165140e-315 0.00000000e+000]
 [5.31410685e-317 6.68534614e-310]]

2. All ones 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. 3x3 array filled with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros array with same shape as given array:
Given array shape: (2, 3)
[[0 0 0]
 [0 0 0]]

5. Ones array with same shape as given array:
[[1 1 1]
 [1 1 1]]

6. Converted list to numpy array:
Original list: [1, 2, 3, 4]
Numpy array: [1 2 3 4]
Type: <class 'numpy.ndarray'>


#### Problem 2: Array Manipulation - Numerical Ranges and Array Indexing
Complete the following tasks:

In [ ]:
import numpy as np

# 1. Create an array with values ranging from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array with values from 10 to 49:")
print(arr_range)
print()

# 2. Create a 3x3 matrix with values ranging from 0 to 8
matrix_3x3 = np.arange(0, 9).reshape(3, 3)
print("2. 3x3 matrix with values from 0 to 8:")
print(matrix_3x3)
print()

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("3. 3x3 identity matrix:")
print(identity_matrix)
print()

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("4. Random array of size 30:")
print(random_array)
print("Mean of the array:", mean_value)
print()

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("5. 10x10 random array:")
print(random_10x10)
print("Minimum value:", min_value)
print("Maximum value:", max_value)
print()

# 6. Create a zero array of size 10 and replace 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Index 4 is the 5th element (0-indexed)
print("6. Zero array with 5th element replaced by 1:")
print(zero_array)
print()

# 7. Reverse an array arr = [1,2,0,0,4,0]
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("7. Original array:", arr)
print("Reversed array:", reversed_arr)
print()

# 8. Create a 2d array with 1 on border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:")
print(border_array)
print()

# 9. Create a 8x8 matrix and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[::2, 1::2] = 1  # Odd rows, even columns
checkerboard[1::2, ::2] = 1  # Even rows, odd columns
print("9. 8x8 checkerboard pattern:")
print(checkerboard)

#### Problem 3: Array Operations
For the following arrays:
- `x = np.array([[1,2],[3,5]])` and `y = np.array([[5,6],[7,8]])`
- `v = np.array([9,10])` and `w = np.array([11,12])`

Complete all the tasks using numpy:

In [ ]:
import numpy as np

# Define the arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("Given arrays:")
print("x =\n", x)
print("y =\n", y)
print("v =", v)
print("w =", w)
print("\n" + "="*50 + "\n")

# 1. Add the two arrays
addition = x + y
print("1. Addition (x + y):")
print(addition)
print()

# 2. Subtract the two arrays
subtraction = x - y
print("2. Subtraction (x - y):")
print(subtraction)
print()

# 3. Multiply the array with any integer of your choice
integer = 3
multiplication = x * integer
print(f"3. Multiply x by {integer}:")
print(multiplication)
print()

# 4. Find the square of each element of the array
square_x = x ** 2
square_y = y ** 2
print("4. Square of each element:")
print("x^2 =\n", square_x)
print("y^2 =\n", square_y)
print()

# 5. Find the dot product between: v and w; x and v; x and y
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("5. Dot products:")
print("v · w =", dot_vw)
print("x · v =", dot_xv)
print("x · y =\n", dot_xy)
print()

# 6. Concatenate x and y along row, and v and w along column
concat_xy_row = np.vstack((x, y))  # or np.concatenate((x, y), axis=0)
concat_vw_col = np.column_stack((v, w))  # or np.vstack((v, w)).T
print("6. Concatenation:")
print("x and y concatenated along rows (vertical stack):")
print(concat_xy_row)
print("\nv and w concatenated along columns:")
print(concat_vw_col)
print()

# 7. Concatenate x and v - this will cause an error
print("7. Attempting to concatenate x and v:")
try:
    concat_xv = np.concatenate((x, v))
    print(concat_xv)
except ValueError as e:
    print(f"Error: {e}")
    print("\nExplanation: The error occurs because x has shape (2, 2) and v has shape (2,).")
    print("The arrays must have compatible shapes for concatenation.")
    print("x is a 2D array while v is a 1D array, and their dimensions don't match.")
    print("To fix this, we need to reshape v or use a different concatenation method.")
    print("\nPossible solution - reshape v to 2D:")
    v_reshaped = v.reshape(1, -1)  # Reshape to (1, 2)
    concat_xv_fixed = np.vstack((x, v_reshaped))
    print("x concatenated with reshaped v:")
    print(concat_xv_fixed)

#### Problem 4: Matrix Operations

**Part 1: Matrix Properties**

For the following arrays:
- `A = np.array([[3,4],[7,8]])` and `B = np.array([[5,3],[2,1]])`

Prove the following with Numpy:

In [ ]:
import numpy as np

# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\n" + "="*50)

# 1. Prove A · A^(-1) = I
print("\n1. Prove A · A^(-1) = I")
print("-" * 30)
A_inv = np.linalg.inv(A)
print("A^(-1) (Inverse of A):")
print(A_inv)
print("\nA · A^(-1):")
result = np.dot(A, A_inv)
print(result)
print("\nIdentity Matrix I:")
I = np.eye(2)
print(I)
print("\nIs A · A^(-1) = I? ", np.allclose(result, I))

# 2. Prove AB ≠ BA
print("\n" + "="*50)
print("\n2. Prove AB ≠ BA")
print("-" * 30)
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB =")
print(AB)
print("\nBA =")
print(BA)
print("\nAre AB and BA equal?", np.array_equal(AB, BA))
print("Therefore, AB ≠ BA (matrix multiplication is not commutative)")

# 3. Prove (AB)^T = B^T · A^T
print("\n" + "="*50)
print("\n3. Prove (AB)^T = B^T · A^T")
print("-" * 30)
AB_transpose = (np.dot(A, B)).T
print("(AB)^T =")
print(AB_transpose)

B_transpose = B.T
A_transpose = A.T
print("\nB^T =")
print(B_transpose)
print("\nA^T =")
print(A_transpose)

BT_AT = np.dot(B_transpose, A_transpose)
print("\nB^T · A^T =")
print(BT_AT)
print("\nIs (AB)^T = B^T · A^T?", np.array_equal(AB_transpose, BT_AT))
print("Verified! ✓")

**Part 2: Solving System of Linear Equations**

Solve the following system of linear equations using the Inverse Method:

```
2x - 3y + z = -1
x - y + 2z = -3
3x + y - z = 9
```

**Hint:** First represent the equation in matrix form AX = B, then solve for X

In [ ]:
import numpy as np

# System of Linear Equations:
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Step 1: Represent in matrix form AX = B
# Coefficient matrix A
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

# Constants vector B
B = np.array([-1, -3, 9])

print("System of Linear Equations:")
print("2x - 3y + z = -1")
print("x - y + 2z = -3")
print("3x + y - z = 9")
print("\n" + "="*50)

print("\nCoefficient Matrix A:")
print(A)
print("\nConstants Vector B:")
print(B)

# Method 1: Using Inverse Method (X = A^(-1) · B)
print("\n" + "="*50)
print("\nMethod 1: Using Inverse Method (X = A^(-1) · B)")
print("-" * 50)

A_inv = np.linalg.inv(A)
print("\nInverse of A (A^(-1)):")
print(A_inv)

X_inverse = np.dot(A_inv, B)
print("\nSolution using Inverse Method:")
print(f"x = {X_inverse[0]}")
print(f"y = {X_inverse[1]}")
print(f"z = {X_inverse[2]}")

# Method 2: Using np.linalg.solve function (more efficient and numerically stable)
print("\n" + "="*50)
print("\nMethod 2: Using np.linalg.solve() function")
print("-" * 50)

X_solve = np.linalg.solve(A, B)
print("\nSolution using np.linalg.solve():")
print(f"x = {X_solve[0]}")
print(f"y = {X_solve[1]}")
print(f"z = {X_solve[2]}")

# Verification: Check if AX = B
print("\n" + "="*50)
print("\nVerification: AX should equal B")
print("-" * 50)
verification = np.dot(A, X_solve)
print("A · X =", verification)
print("B =", B)
print("Is AX = B?", np.allclose(verification, B))

# Additional exploration of linalg module
print("\n" + "="*50)
print("\nAdditional np.linalg functions:")
print("-" * 50)
print("Determinant of A:", np.linalg.det(A))
print("Rank of A:", np.linalg.matrix_rank(A))
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues of A:", eigenvalues)
print("Matrix norm of A:", np.linalg.norm(A))

### 4.2 Experiment: How Fast is Numpy?

In this exercise, we will compare the performance of operations using plain Python lists versus NumPy arrays.

We will test the following operations:
1. Element-wise Addition
2. Element-wise Multiplication
3. Dot Product
4. Matrix Multiplication

#### 1. Element-wise Addition

In [ ]:
import numpy as np
import time

size = 1_000_000

# Using Python Lists
print("=" * 60)
print("1. ELEMENT-WISE ADDITION")
print("=" * 60)
print(f"\nSize: {size:,} elements\n")

# Create two Python lists
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise addition using Python lists
start_time = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
python_time = time.time() - start_time
print(f"Python Lists Time: {python_time:.6f} seconds")

# Using NumPy Arrays
# Create two NumPy arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for element-wise addition using NumPy
start_time = time.time()
result_array = array1 + array2
numpy_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"\nSpeedup: {speedup:.2f}x faster with NumPy")
print(f"NumPy is {speedup:.2f} times faster than Python lists!")

#### 2. Element-wise Multiplication

In [ ]:
import numpy as np
import time

size = 1_000_000

print("=" * 60)
print("2. ELEMENT-WISE MULTIPLICATION")
print("=" * 60)
print(f"\nSize: {size:,} elements\n")

# Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

# Measure time for element-wise multiplication using Python lists
start_time = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
python_time = time.time() - start_time
print(f"Python Lists Time: {python_time:.6f} seconds")

# Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for element-wise multiplication using NumPy
start_time = time.time()
result_array = array1 * array2
numpy_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"\nSpeedup: {speedup:.2f}x faster with NumPy")
print(f"NumPy is {speedup:.2f} times faster than Python lists!")

#### 3. Dot Product

In [ ]:
import numpy as np
import time

size = 1_000_000

print("=" * 60)
print("3. DOT PRODUCT")
print("=" * 60)
print(f"\nSize: {size:,} elements\n")

# Using Python Lists
list1 = list(range(size))
list2 = list(range(size))

# Measure time for dot product using Python lists
start_time = time.time()
result_list = sum([list1[i] * list2[i] for i in range(size)])
python_time = time.time() - start_time
print(f"Python Lists Time: {python_time:.6f} seconds")

# Using NumPy Arrays
array1 = np.arange(size)
array2 = np.arange(size)

# Measure time for dot product using NumPy
start_time = time.time()
result_array = np.dot(array1, array2)
numpy_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"\nSpeedup: {speedup:.2f}x faster with NumPy")
print(f"NumPy is {speedup:.2f} times faster than Python lists!")

# Verify results are the same
print(f"\nVerification - Results match: {result_list == result_array}")

#### 4. Matrix Multiplication

In [ ]:
import numpy as np
import time

size = 1000  # 1000x1000 matrices

print("=" * 60)
print("4. MATRIX MULTIPLICATION")
print("=" * 60)
print(f"\nMatrix Size: {size}x{size}\n")

# Using Python Lists
# Create two 1000x1000 matrices using Python lists
list_matrix1 = [[i + j for j in range(size)] for i in range(size)]
list_matrix2 = [[i - j for j in range(size)] for i in range(size)]

# Measure time for matrix multiplication using Python lists
start_time = time.time()
result_list = [[sum(list_matrix1[i][k] * list_matrix2[k][j] for k in range(size))
                for j in range(size)] for i in range(size)]
python_time = time.time() - start_time
print(f"Python Lists Time: {python_time:.6f} seconds")

# Using NumPy Arrays
# Create two 1000x1000 matrices using NumPy
array_matrix1 = np.array([[i + j for j in range(size)] for i in range(size)])
array_matrix2 = np.array([[i - j for j in range(size)] for i in range(size)])

# Alternative: More efficient way to create the same matrices
# array_matrix1 = np.arange(size).reshape(-1, 1) + np.arange(size)
# array_matrix2 = np.arange(size).reshape(-1, 1) - np.arange(size)

# Measure time for matrix multiplication using NumPy
start_time = time.time()
result_array = np.dot(array_matrix1, array_matrix2)
# Alternative: result_array = array_matrix1 @ array_matrix2
numpy_time = time.time() - start_time
print(f"NumPy Arrays Time: {numpy_time:.6f} seconds")

# Performance comparison
speedup = python_time / numpy_time
print(f"\nSpeedup: {speedup:.2f}x faster with NumPy")
print(f"NumPy is {speedup:.2f} times faster than Python lists!")
print(f"\nThis demonstrates the MASSIVE performance advantage of NumPy,")
print(f"especially for computationally intensive operations like matrix multiplication!")